name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched the [existing issues](https://github.com/kyamagu/psd2svg/issues) and this bug has not been reported
          required: true
        - label: I have reviewed the [Known Limitations](https://psd2svg.readthedocs.io/en/latest/limitations.html) and this is not a known limitation
          required: true
        - label: This is not a security vulnerability (those should be reported via [SECURITY.md](https://github.com/kyamagu/psd2svg/blob/main/SECURITY.md))
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I convert a PSD file with..., the output shows...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Create a PSD with...
        2. Run the command...
        3. Observe the output...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The SVG should show...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: The SVG instead shows...
    validations:
      required: true

  - type: textarea
    id: psd-file
    attributes:
      label: Sample PSD File
      description: |
        If possible, attach a minimal PSD file that demonstrates the issue.
        You can drag and drop files into this text area.
      placeholder: Drag and drop a PSD file here, or provide a link to download it

  - type: input
    id: version
    attributes:
      label: psd2svg Version
      description: Run `pip show psd2svg` to get the version
      placeholder: "0.10.1"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "Python 3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages or Logs
      description: Any error messages, tracebacks, or relevant logs
      render: shell
      placeholder: |
        Traceback (most recent call last):
          File ...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, workarounds you've tried, etc.)
      placeholder: I also tried... but...
