import contextlib
import xml.etree.ElementTree as ET
from typing import Iterator, Protocol

from PIL import Image
from psd_tools import PSDImage
from psd_tools.api import adjustments, layers
from psd_tools.psd.descriptor import Descriptor


class ConverterProtocol(Protocol):
    """Converter state protocol."""

    psd: PSDImage
    svg: ET.Element
    current: ET.Element
    images: list[Image.Image]

    def add_layer(self, layer: layers.Layer, **attrib: str) -> ET.Element | None: ...
    def add_group(self, layer: layers.Group, **attrib: str) -> ET.Element | None: ...
    def add_pixel(self, layer: layers.Layer, **attrib: str) -> ET.Element | None: ...
    def add_shape(
        self, layer: layers.ShapeLayer, **attrib: str
    ) -> ET.Element | None: ...
    def add_adjustment(
        self, layer: layers.AdjustmentLayer, **attrib: str
    ) -> ET.Element | None: ...
    def add_type(self, layer: layers.TypeLayer, **attrib: str) -> ET.Element | None: ...
    def add_fill(self, layer: layers.FillLayer, **attrib: str) -> ET.Element | None: ...

    # Layer attributes
    def set_layer_attributes(self, layer: layers.Layer, node: ET.Element) -> None: ...
    def set_isolation(self, layer: layers.Layer, node: ET.Element) -> None: ...
    def set_mask(self, layer: layers.Layer, node: ET.Element) -> None: ...
    def set_opacity(self, opacity: float, node: ET.Element) -> None: ...
    def set_blend_mode(self, psd_mode: bytes | str, node: ET.Element) -> None: ...
    def add_linear_gradient(self, setting: Descriptor) -> ET.Element: ...
    def add_radial_gradient(self, setting: Descriptor) -> ET.Element: ...
    def add_pattern(self, psdimage: PSDImage, descriptor: Descriptor) -> ET.Element: ...

    # Shape methods
    def create_shape(self, layer: layers.ShapeLayer, **attrib) -> ET.Element: ...
    
    # Paint methods
    def apply_vector_fill(
        self, layer: layers.ShapeLayer | adjustments.FillLayer, target: ET.Element
    ) -> None: ...
    def apply_vector_stroke(
        self, layer: layers.ShapeLayer | adjustments.FillLayer, target: ET.Element
    ) -> None: ...
    def set_fill(
        self, layer: layers.ShapeLayer | adjustments.FillLayer, node: ET.Element
    ) -> None: ...
    def set_stroke(
        self, layer: layers.ShapeLayer | adjustments.FillLayer, node: ET.Element
    ) -> None: ...

    # Layer effects
    def apply_background_effects(
        self, layer: layers.Layer, target: ET.Element, insert_before_target: bool = True
    ) -> None: ...
    def apply_overlay_effects(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_drop_shadow_effect(
        self,
        layer: layers.Layer,
        target: ET.Element,
        insert_before_target: bool = False,
    ) -> None: ...
    def apply_outer_glow_effect(
        self,
        layer: layers.Layer,
        target: ET.Element,
        insert_before_target: bool = False,
    ) -> None: ...
    def apply_color_overlay_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_gradient_overlay_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_pattern_overlay_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_inner_shadow_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_inner_glow_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_satin_effect(self, layer: layers.Layer, target: ET.Element) -> None: ...
    def apply_bevel_emboss_effect(
        self, layer: layers.Layer, target: ET.Element
    ) -> None: ...
    def apply_stroke_effect(self, layer: layers.Layer, target: ET.Element) -> None: ...

    # Utilities
    def auto_id(self, prefix: str = "") -> str: ...
    @contextlib.contextmanager
    def set_current(self, node: ET.Element) -> Iterator[None]: ...
