from typing import Union

from psd_tools.constants import BlendMode

# https://helpx.adobe.com/photoshop/using/blending-modes.html
BLEND_MODE: dict[Union[BlendMode, str], str] = {
    # Layer modes.
    BlendMode.PASS_THROUGH: "normal",
    BlendMode.NORMAL: "normal",
    BlendMode.DISSOLVE: "normal",
    BlendMode.DARKEN: "darken",
    BlendMode.MULTIPLY: "multiply",
    BlendMode.COLOR_BURN: "color-burn",
    BlendMode.LINEAR_BURN: "plus-darker",
    BlendMode.DARKER_COLOR: "darken",
    BlendMode.LIGHTEN: "lighten",
    BlendMode.SCREEN: "screen",
    BlendMode.COLOR_DODGE: "color-dodge",
    BlendMode.LINEAR_DODGE: "plus-lighter",
    BlendMode.LIGHTER_COLOR: "lighten",
    BlendMode.OVERLAY: "overlay",
    BlendMode.SOFT_LIGHT: "soft-light",
    BlendMode.HARD_LIGHT: "hard-light",
    BlendMode.VIVID_LIGHT: "lighten",
    BlendMode.LINEAR_LIGHT: "darken",
    BlendMode.PIN_LIGHT: "normal",
    BlendMode.HARD_MIX: "normal",
    BlendMode.DIFFERENCE: "difference",
    BlendMode.EXCLUSION: "exclusion",
    BlendMode.SUBTRACT: "difference",
    BlendMode.DIVIDE: "difference",
    BlendMode.HUE: "hue",
    BlendMode.SATURATION: "saturation",
    BlendMode.COLOR: "color",
    BlendMode.LUMINOSITY: "luminosity",
    # psd-tools API modes.
    "pass through": "normal",
    "dissolve": "normal",
    "darken": "darken",
    "multiply": "multiply",
    "color burn": "color-burn",
    "linear burn": "plus-darker",
    "darker color": "darken",
    "lighten": "lighten",
    "screen": "screen",
    "color dodge": "color-dodge",
    "linear dodge": "plus-lighter",
    "lighter color": "lighten",
    "overlay": "overlay",
    "soft light": "soft-light",
    "hard light": "hard-light",
    "vivid light": "lighten",
    "linear light": "darken",
    "pin light": "normal",
    "hard mix": "normal",
    "difference": "difference",
    "exclusion": "exclusion",
    "subtract": "difference",
    "divide": "difference",
    "hue": "hue",
    "saturation": "saturation",
    "color": "color",
    "luminosity": "luminosity",
    # Descriptor values.
    "linearnormaldodge": "plus-lighter",
    "linearnormalburn": "plus-darker",
}